catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.1
  vitest: 5.0.0
packages:
  - perf
allowBuilds:
  es5-ext: false
  esbuild: true
  vue-demi: false
  workerd: true
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    typescript: "*"
    vite: "*"
overrides:
  vite@*: "catalog:"
