catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: 5.0.2
packages:
  - perf
allowBuilds:
  es5-ext: false
  esbuild: true
  vue-demi: false
  workerd: true
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    typescript: "*"
    vite: "*"
overrides:
  vite@*: "catalog:"
