import { defineConfig, Feedback, McpSource, Changelog } from "vocs/config";
import { sidebar } from "./sidebar/sidebar";
import changelogData from "./src/data/changelog.json";

export const sponsors = {
  collaborators: [
    {
      name: "Paradigm",
      link: "https://paradigm.xyz",
      image:
        "https://raw.githubusercontent.com/wevm/.github/main/content/sponsors/paradigm-light.svg",
    },
    {
      name: "Tempo",
      link: "https://tempo.xyz",
      image:
        "https://raw.githubusercontent.com/wevm/.github/main/content/sponsors/tempo-light.svg",
    },
  ],
};

export default defineConfig({
  codeHighlight: {
    langs: [],
    langAlias: {
      gitignore: "text",
    },
  },
  // light: '#f98a1a', -- darker orange than the one below
  accentColor: "light-dark(#f6b128, #f9c22f)",
  title: "foundry - Ethereum Development Framework",
  description:
    "Use Foundry's Forge, Cast, Anvil, and Chisel tools to build, test, fuzz, debug, deploy, and inspect Ethereum smart contracts.",
  baseUrl: "https://www.getfoundry.sh",
  // Keep assets on the current origin so Vercel previews do not load them cross-origin.
  // `baseUrl` still provides the production origin for canonical and Open Graph metadata.
  head: {
    base: false,
  },
  rootDir: ".",
  sidebar,
  // Foundry publishes a nightly prerelease every day, so fetching from the
  // GitHub releases feed directly surfaces few or no stable releases. The
  // changelog instead renders src/data/changelog.json, which is generated by
  // scripts/fetch-changelog.ts from stable GitHub releases.
  changelog: Changelog.from({
    type: "foundry",
    async fetch(options = {}) {
      const { limit = 50 } = options;
      return changelogData.releases.slice(0, limit).map((release) => ({ ...release }));
    },
  }),
  feedback: Feedback.slack(),
  mcp: {
    enabled: true,
    sources: [McpSource.github({ repo: "foundry-rs/foundry" })],
  },
  editLink: {
    link: "https://github.com/foundry-rs/book/edit/master/src/pages/:path",
    text: "Suggest changes on GitHub",
  },
  logoUrl: "/foundry-logo.png",
  iconUrl: "/foundry-logo.png",
  ogImageUrl: "/og-image.png",
  socials: [
    {
      link: "https://github.com/foundry-rs/foundry",
      icon: "github",
    },
    {
      link: "https://t.me/foundry_support",
      icon: "telegram",
    },
  ],
  topNav: [
    {
      link: "/introduction/getting-started",
      text: "Docs",
    },
    {
      link: "/guides",
      text: "Guides",
    },
    {
      link: "/guides/tempo",
      match: "/guides/tempo",
      text: "Tempo",
    },
    {
      text: "Reference",
      items: [
        {
          text: "Overview",
          link: "/reference",
        },
        {
          text: "forge",
          link: "/reference/forge/forge",
        },
        {
          text: "cast",
          link: "/reference/cast/cast",
        },
        {
          text: "anvil",
          link: "/reference/anvil/anvil",
        },
        {
          text: "chisel",
          link: "/reference/chisel/chisel",
        },
        {
          text: "Cheatcodes",
          link: "/reference/cheatcodes/overview",
        },
        {
          text: "Forge Std",
          link: "/reference/forge-std/overview",
        },
        {
          text: "Configuration",
          link: "/config/reference/overview",
        },
      ],
    },
    {
      link: "/benchmarks",
      text: "Benchmarks",
    },
    {
      text: "Changelog",
      link: "/changelog",
    },
  ],
});
