import { SidebarItem } from "vocs";

export const castCliReference: SidebarItem = {
    text: "Reference",
    collapsed: true,
    items: [
        { text: "cast", link: "/cast/reference/cast" },
        {
            text: "ABI Commands",
            collapsed: true,
            items: [
                { text: "cast 4byte", link: "/cast/reference/4byte" },
                { text: "cast 4byte-calldata", link: "/cast/reference/4byte-calldata" },
                { text: "cast 4byte-event", link: "/cast/reference/4byte-event" },
                { text: "cast abi-encode", link: "/cast/reference/abi-encode" },
                { text: "cast calldata", link: "/cast/reference/calldata" },
                { text: "cast decode-abi", link: "/cast/reference/decode-abi" },
                { text: "cast decode-calldata", link: "/cast/reference/decode-calldata" },
                { text: "cast pretty-calldata", link: "/cast/reference/pretty-calldata" },
                { text: "cast selectors", link: "/cast/reference/selectors" },
                { text: "cast upload-signature", link: "/cast/reference/upload-signature" },
            ],
        },
        {
            text: "Account Commands",
            collapsed: true,
            items: [
                { text: "cast balance", link: "/cast/reference/balance" },
                { text: "cast code", link: "/cast/reference/code" },
                { text: "cast codesize", link: "/cast/reference/codesize" },
                { text: "cast nonce", link: "/cast/reference/nonce" },
                { text: "cast proof", link: "/cast/reference/proof" },
                { text: "cast storage", link: "/cast/reference/storage" },
            ],
        },
        {
            text: "Block Commands",
            collapsed: true,
            items: [
                { text: "cast age", link: "/cast/reference/age" },
                { text: "cast block", link: "/cast/reference/block" },
                { text: "cast block-number", link: "/cast/reference/block-number" },
                { text: "cast find-block", link: "/cast/reference/find-block" },
                { text: "cast gas-price", link: "/cast/reference/gas-price" },
            ],
        },
        {
            text: "Chain Commands",
            collapsed: true,
            items: [
                { text: "cast chain", link: "/cast/reference/chain" },
                { text: "cast chain-id", link: "/cast/reference/chain-id" },
                { text: "cast client", link: "/cast/reference/client" },
            ],
        },
        {
            text: "Conversion Commands",
            collapsed: true,
            items: [
                { text: "cast format-bytes32-string", link: "/cast/reference/format-bytes32-string" },
                { text: "cast from-bin", link: "/cast/reference/from-bin" },
                { text: "cast from-fixed-point", link: "/cast/reference/from-fixed-point" },
                { text: "cast from-rlp", link: "/cast/reference/from-rlp" },
                { text: "cast from-utf8", link: "/cast/reference/from-utf8" },
                { text: "cast from-wei", link: "/cast/reference/from-wei" },
                { text: "cast parse-bytes32-address", link: "/cast/reference/parse-bytes32-address" },
                { text: "cast parse-bytes32-string", link: "/cast/reference/parse-bytes32-string" },
                { text: "cast shl", link: "/cast/reference/shl" },
                { text: "cast shr", link: "/cast/reference/shr" },
                { text: "cast to-ascii", link: "/cast/reference/to-ascii" },
                { text: "cast to-base", link: "/cast/reference/to-base" },
                { text: "cast to-bytes32", link: "/cast/reference/to-bytes32" },
                { text: "cast to-dec", link: "/cast/reference/to-dec" },
                { text: "cast to-fixed-point", link: "/cast/reference/to-fixed-point" },
                { text: "cast to-hex", link: "/cast/reference/to-hex" },
                { text: "cast to-hexdata", link: "/cast/reference/to-hexdata" },
                { text: "cast to-int256", link: "/cast/reference/to-int256" },
                { text: "cast to-rlp", link: "/cast/reference/to-rlp" },
                { text: "cast to-uint256", link: "/cast/reference/to-uint256" },
                { text: "cast to-unit", link: "/cast/reference/to-unit" },
                { text: "cast to-wei", link: "/cast/reference/to-wei" },
            ],
        },
        {
            text: "ENS Commands",
            collapsed: true,
            items: [
                { text: "cast lookup-address", link: "/cast/reference/lookup-address" },
                { text: "cast namehash", link: "/cast/reference/namehash" },
                { text: "cast resolve-name", link: "/cast/reference/resolve-name" },
            ],
        },
        {
            text: "Etherscan Commands",
            collapsed: true,
            items: [
                { text: "cast source", link: "/cast/reference/source" },
            ],
        },
        {
            text: "General Commands",
            collapsed: true,
            items: [
                { text: "cast completions", link: "/cast/reference/completions" },
            ],
        },
        {
            text: "Transaction Commands",
            collapsed: true,
            items: [
                { text: "cast access-list", link: "/cast/reference/access-list" },
                { text: "cast call", link: "/cast/reference/call" },
                { text: "cast estimate", link: "/cast/reference/estimate" },
                { text: "cast logs", link: "/cast/reference/logs" },
                { text: "cast mktx", link: "/cast/reference/mktx" },
                { text: "cast publish", link: "/cast/reference/publish" },
                { text: "cast receipt", link: "/cast/reference/receipt" },
                { text: "cast rpc", link: "/cast/reference/rpc" },
                { text: "cast run", link: "/cast/reference/run" },
                { text: "cast send", link: "/cast/reference/send" },
                { text: "cast tx", link: "/cast/reference/tx" },
            ],
        },
        {
            text: "Utility Commands",
            collapsed: true,
            items: [
                { text: "cast address-zero", link: "/cast/reference/address-zero" },
                { text: "cast admin", link: "/cast/reference/admin" },
                { text: "cast artifact", link: "/cast/reference/artifact" },
                { text: "cast base-fee", link: "/cast/reference/base-fee" },
                { text: "cast bind", link: "/cast/reference/bind" },
                { text: "cast call --create", link: "/cast/reference/call/--create" },
                { text: "cast codehash", link: "/cast/reference/codehash" },
                { text: "cast compute-address", link: "/cast/reference/compute-address" },
                { text: "cast concat-hex", link: "/cast/reference/concat-hex" },
                { text: "cast constructor-args", link: "/cast/reference/constructor-args" },
                { text: "cast create2", link: "/cast/reference/create2" },
                { text: "cast creation-code", link: "/cast/reference/creation-code" },
                { text: "cast da-estimate", link: "/cast/reference/da-estimate" },
                { text: "cast decode-error", link: "/cast/reference/decode-error" },
                { text: "cast decode-event", link: "/cast/reference/decode-event" },
                { text: "cast decode-string", link: "/cast/reference/decode-string" },
                { text: "cast decode-transaction", link: "/cast/reference/decode-transaction" },
                { text: "cast disassemble", link: "/cast/reference/disassemble" },
                { text: "cast estimate --create", link: "/cast/reference/estimate/--create" },
                { text: "cast format-units", link: "/cast/reference/format-units" },
                { text: "cast generate-fig-spec", link: "/cast/reference/generate-fig-spec" },
                { text: "cast hash-message", link: "/cast/reference/hash-message" },
                { text: "cast hash-zero", link: "/cast/reference/hash-zero" },
                { text: "cast implementation", link: "/cast/reference/implementation" },
                { text: "cast index", link: "/cast/reference/index" },
                { text: "cast index-erc7201", link: "/cast/reference/index-erc7201" },
                { text: "cast interface", link: "/cast/reference/interface" },
                { text: "cast keccak", link: "/cast/reference/keccak" },
                { text: "cast max-int", link: "/cast/reference/max-int" },
                { text: "cast max-uint", link: "/cast/reference/max-uint" },
                { text: "cast min-int", link: "/cast/reference/min-int" },
                { text: "cast mktx --create", link: "/cast/reference/mktx/--create" },
                { text: "cast pad", link: "/cast/reference/pad" },
                { text: "cast parse-units", link: "/cast/reference/parse-units" },
                { text: "cast recover-authority", link: "/cast/reference/recover-authority" },
                { text: "cast send --create", link: "/cast/reference/send/--create" },
                { text: "cast sig", link: "/cast/reference/sig" },
                { text: "cast sig-event", link: "/cast/reference/sig-event" },
                { text: "cast storage-root", link: "/cast/reference/storage-root" },
                { text: "cast to-check-sum-address", link: "/cast/reference/to-check-sum-address" },
                { text: "cast to-utf8", link: "/cast/reference/to-utf8" },
                { text: "cast tx-pool", link: "/cast/reference/tx-pool" },
                { text: "cast tx-pool content", link: "/cast/reference/tx-pool/content" },
                { text: "cast tx-pool content-from", link: "/cast/reference/tx-pool/content-from" },
                { text: "cast tx-pool inspect", link: "/cast/reference/tx-pool/inspect" },
                { text: "cast tx-pool status", link: "/cast/reference/tx-pool/status" },
                { text: "cast wallet address", link: "/cast/reference/wallet/address" },
                { text: "cast wallet change-password", link: "/cast/reference/wallet/change-password" },
                { text: "cast wallet decrypt-keystore", link: "/cast/reference/wallet/decrypt-keystore" },
                { text: "cast wallet import", link: "/cast/reference/wallet/import" },
                { text: "cast wallet list", link: "/cast/reference/wallet/list" },
                { text: "cast wallet new", link: "/cast/reference/wallet/new" },
                { text: "cast wallet new-mnemonic", link: "/cast/reference/wallet/new-mnemonic" },
                { text: "cast wallet private-key", link: "/cast/reference/wallet/private-key" },
                { text: "cast wallet public-key", link: "/cast/reference/wallet/public-key" },
                { text: "cast wallet remove", link: "/cast/reference/wallet/remove" },
                { text: "cast wallet sign", link: "/cast/reference/wallet/sign" },
                { text: "cast wallet sign-auth", link: "/cast/reference/wallet/sign-auth" },
                { text: "cast wallet vanity", link: "/cast/reference/wallet/vanity" },
                { text: "cast wallet verify", link: "/cast/reference/wallet/verify" },
            ],
        },
        {
            text: "Wallet Commands",
            collapsed: true,
            items: [
                { text: "cast wallet", link: "/cast/reference/wallet" },
            ],
        },
    ],
};
