import { SidebarItem } from "vocs";

export const castCliReference: SidebarItem = {
    text: "Reference",
    collapsed: true,
    items: [
        { text: "cast", link: "/reference/cast/cast" },
        {
            text: "ABI Commands",
            collapsed: true,
            items: [
                { text: "cast 4byte", link: "/reference/cast/4byte" },
                { text: "cast 4byte-calldata", link: "/reference/cast/4byte-calldata" },
                { text: "cast 4byte-event", link: "/reference/cast/4byte-event" },
                { text: "cast abi-encode", link: "/reference/cast/abi-encode" },
                { text: "cast calldata", link: "/reference/cast/calldata" },
                { text: "cast decode-abi", link: "/reference/cast/decode-abi" },
                { text: "cast decode-calldata", link: "/reference/cast/decode-calldata" },
                { text: "cast pretty-calldata", link: "/reference/cast/pretty-calldata" },
                { text: "cast selectors", link: "/reference/cast/selectors" },
                { text: "cast upload-signature", link: "/reference/cast/upload-signature" },
            ],
        },
        {
            text: "Account Commands",
            collapsed: true,
            items: [
                { text: "cast balance", link: "/reference/cast/balance" },
                { text: "cast code", link: "/reference/cast/code" },
                { text: "cast codesize", link: "/reference/cast/codesize" },
                { text: "cast erc20-token balance", link: "/reference/cast/erc20-token/balance" },
                { text: "cast nonce", link: "/reference/cast/nonce" },
                { text: "cast proof", link: "/reference/cast/proof" },
                { text: "cast storage", link: "/reference/cast/storage" },
            ],
        },
        {
            text: "Block Commands",
            collapsed: true,
            items: [
                { text: "cast age", link: "/reference/cast/age" },
                { text: "cast block", link: "/reference/cast/block" },
                { text: "cast block-number", link: "/reference/cast/block-number" },
                { text: "cast find-block", link: "/reference/cast/find-block" },
                { text: "cast gas-price", link: "/reference/cast/gas-price" },
            ],
        },
        {
            text: "Chain Commands",
            collapsed: true,
            items: [
                { text: "cast chain", link: "/reference/cast/chain" },
                { text: "cast chain-id", link: "/reference/cast/chain-id" },
                { text: "cast client", link: "/reference/cast/client" },
            ],
        },
        {
            text: "Conversion Commands",
            collapsed: true,
            items: [
                { text: "cast format-bytes32-string", link: "/reference/cast/format-bytes32-string" },
                { text: "cast from-bin", link: "/reference/cast/from-bin" },
                { text: "cast from-fixed-point", link: "/reference/cast/from-fixed-point" },
                { text: "cast from-rlp", link: "/reference/cast/from-rlp" },
                { text: "cast from-utf8", link: "/reference/cast/from-utf8" },
                { text: "cast from-wei", link: "/reference/cast/from-wei" },
                { text: "cast parse-bytes32-address", link: "/reference/cast/parse-bytes32-address" },
                { text: "cast parse-bytes32-string", link: "/reference/cast/parse-bytes32-string" },
                { text: "cast shl", link: "/reference/cast/shl" },
                { text: "cast shr", link: "/reference/cast/shr" },
                { text: "cast to-ascii", link: "/reference/cast/to-ascii" },
                { text: "cast to-base", link: "/reference/cast/to-base" },
                { text: "cast to-bytes32", link: "/reference/cast/to-bytes32" },
                { text: "cast to-dec", link: "/reference/cast/to-dec" },
                { text: "cast to-fixed-point", link: "/reference/cast/to-fixed-point" },
                { text: "cast to-hex", link: "/reference/cast/to-hex" },
                { text: "cast to-hexdata", link: "/reference/cast/to-hexdata" },
                { text: "cast to-int256", link: "/reference/cast/to-int256" },
                { text: "cast to-rlp", link: "/reference/cast/to-rlp" },
                { text: "cast to-uint256", link: "/reference/cast/to-uint256" },
                { text: "cast to-unit", link: "/reference/cast/to-unit" },
                { text: "cast to-wei", link: "/reference/cast/to-wei" },
            ],
        },
        {
            text: "ENS Commands",
            collapsed: true,
            items: [
                { text: "cast lookup-address", link: "/reference/cast/lookup-address" },
                { text: "cast namehash", link: "/reference/cast/namehash" },
                { text: "cast resolve-name", link: "/reference/cast/resolve-name" },
            ],
        },
        {
            text: "Etherscan Commands",
            collapsed: true,
            items: [
                { text: "cast source", link: "/reference/cast/source" },
            ],
        },
        {
            text: "General Commands",
            collapsed: true,
            items: [
                { text: "cast completions", link: "/reference/cast/completions" },
            ],
        },
        {
            text: "Transaction Commands",
            collapsed: true,
            items: [
                { text: "cast access-list", link: "/reference/cast/access-list" },
                { text: "cast call", link: "/reference/cast/call" },
                { text: "cast estimate", link: "/reference/cast/estimate" },
                { text: "cast logs", link: "/reference/cast/logs" },
                { text: "cast mktx", link: "/reference/cast/mktx" },
                { text: "cast publish", link: "/reference/cast/publish" },
                { text: "cast receipt", link: "/reference/cast/receipt" },
                { text: "cast rpc", link: "/reference/cast/rpc" },
                { text: "cast run", link: "/reference/cast/run" },
                { text: "cast send", link: "/reference/cast/send" },
                { text: "cast tx", link: "/reference/cast/tx" },
            ],
        },
        {
            text: "Utility Commands",
            collapsed: true,
            items: [
                { text: "cast abi-encode-event", link: "/reference/cast/abi-encode-event" },
                { text: "cast address-zero", link: "/reference/cast/address-zero" },
                { text: "cast admin", link: "/reference/cast/admin" },
                { text: "cast artifact", link: "/reference/cast/artifact" },
                { text: "cast b2e-payload", link: "/reference/cast/b2e-payload" },
                { text: "cast base-fee", link: "/reference/cast/base-fee" },
                { text: "cast bind", link: "/reference/cast/bind" },
                { text: "cast call --create", link: "/reference/cast/call/--create" },
                { text: "cast codehash", link: "/reference/cast/codehash" },
                { text: "cast compute-address", link: "/reference/cast/compute-address" },
                { text: "cast concat-hex", link: "/reference/cast/concat-hex" },
                { text: "cast constructor-args", link: "/reference/cast/constructor-args" },
                { text: "cast create2", link: "/reference/cast/create2" },
                { text: "cast creation-code", link: "/reference/cast/creation-code" },
                { text: "cast da-estimate", link: "/reference/cast/da-estimate" },
                { text: "cast decode-error", link: "/reference/cast/decode-error" },
                { text: "cast decode-event", link: "/reference/cast/decode-event" },
                { text: "cast decode-string", link: "/reference/cast/decode-string" },
                { text: "cast decode-transaction", link: "/reference/cast/decode-transaction" },
                { text: "cast disassemble", link: "/reference/cast/disassemble" },
                { text: "cast erc20-token", link: "/reference/cast/erc20-token" },
                { text: "cast erc20-token allowance", link: "/reference/cast/erc20-token/allowance" },
                { text: "cast erc20-token approve", link: "/reference/cast/erc20-token/approve" },
                { text: "cast erc20-token burn", link: "/reference/cast/erc20-token/burn" },
                { text: "cast erc20-token decimals", link: "/reference/cast/erc20-token/decimals" },
                { text: "cast erc20-token mint", link: "/reference/cast/erc20-token/mint" },
                { text: "cast erc20-token name", link: "/reference/cast/erc20-token/name" },
                { text: "cast erc20-token symbol", link: "/reference/cast/erc20-token/symbol" },
                { text: "cast erc20-token total-supply", link: "/reference/cast/erc20-token/total-supply" },
                { text: "cast erc20-token transfer", link: "/reference/cast/erc20-token/transfer" },
                { text: "cast estimate --create", link: "/reference/cast/estimate/--create" },
                { text: "cast format-units", link: "/reference/cast/format-units" },
                { text: "cast hash-message", link: "/reference/cast/hash-message" },
                { text: "cast hash-zero", link: "/reference/cast/hash-zero" },
                { text: "cast implementation", link: "/reference/cast/implementation" },
                { text: "cast index", link: "/reference/cast/index" },
                { text: "cast index-erc7201", link: "/reference/cast/index-erc7201" },
                { text: "cast interface", link: "/reference/cast/interface" },
                { text: "cast keccak", link: "/reference/cast/keccak" },
                { text: "cast max-int", link: "/reference/cast/max-int" },
                { text: "cast max-uint", link: "/reference/cast/max-uint" },
                { text: "cast min-int", link: "/reference/cast/min-int" },
                { text: "cast mktx --create", link: "/reference/cast/mktx/--create" },
                { text: "cast pad", link: "/reference/cast/pad" },
                { text: "cast parse-units", link: "/reference/cast/parse-units" },
                { text: "cast recover-authority", link: "/reference/cast/recover-authority" },
                { text: "cast send --create", link: "/reference/cast/send/--create" },
                { text: "cast sig", link: "/reference/cast/sig" },
                { text: "cast sig-event", link: "/reference/cast/sig-event" },
                { text: "cast storage-root", link: "/reference/cast/storage-root" },
                { text: "cast to-check-sum-address", link: "/reference/cast/to-check-sum-address" },
                { text: "cast to-utf8", link: "/reference/cast/to-utf8" },
                { text: "cast tx-pool", link: "/reference/cast/tx-pool" },
                { text: "cast tx-pool content", link: "/reference/cast/tx-pool/content" },
                { text: "cast tx-pool content-from", link: "/reference/cast/tx-pool/content-from" },
                { text: "cast tx-pool inspect", link: "/reference/cast/tx-pool/inspect" },
                { text: "cast tx-pool status", link: "/reference/cast/tx-pool/status" },
                { text: "cast wallet address", link: "/reference/cast/wallet/address" },
                { text: "cast wallet change-password", link: "/reference/cast/wallet/change-password" },
                { text: "cast wallet decrypt-keystore", link: "/reference/cast/wallet/decrypt-keystore" },
                { text: "cast wallet derive", link: "/reference/cast/wallet/derive" },
                { text: "cast wallet import", link: "/reference/cast/wallet/import" },
                { text: "cast wallet list", link: "/reference/cast/wallet/list" },
                { text: "cast wallet new", link: "/reference/cast/wallet/new" },
                { text: "cast wallet new-mnemonic", link: "/reference/cast/wallet/new-mnemonic" },
                { text: "cast wallet private-key", link: "/reference/cast/wallet/private-key" },
                { text: "cast wallet public-key", link: "/reference/cast/wallet/public-key" },
                { text: "cast wallet remove", link: "/reference/cast/wallet/remove" },
                { text: "cast wallet sign", link: "/reference/cast/wallet/sign" },
                { text: "cast wallet sign-auth", link: "/reference/cast/wallet/sign-auth" },
                { text: "cast wallet vanity", link: "/reference/cast/wallet/vanity" },
                { text: "cast wallet verify", link: "/reference/cast/wallet/verify" },
            ],
        },
        {
            text: "Wallet Commands",
            collapsed: true,
            items: [
                { text: "cast wallet", link: "/reference/cast/wallet" },
            ],
        },
    ],
};
