import { SidebarItem } from "vocs";

export const cmdReference: SidebarItem[] = [
  {
    text: 'Forge Commands',
    collapsed: true,
    items: [
      {
        text: 'General Commands',
        link: '/reference/forge/general-commands',
        items: [
          { text: 'forge', link: '/reference/forge/forge' },
          { text: 'forge help', link: '/reference/forge/forge-help' },
          { text: 'forge completions', link: '/reference/forge/forge-completions' },
        ],
      },
      {
        text: 'Project Commands',
        link: '/reference/forge/project-commands',
        items: [
          { text: 'forge init', link: '/reference/forge/forge-init' },
          { text: 'forge clone', link: '/reference/forge/forge-clone' },
          { text: 'forge install', link: '/reference/forge/forge-install' },
          { text: 'forge update', link: '/reference/forge/forge-update' },
          { text: 'forge remove', link: '/reference/forge/forge-remove' },
          { text: 'forge config', link: '/reference/forge/forge-config' },
          { text: 'forge remappings', link: '/reference/forge/forge-remappings' },
          { text: 'forge tree', link: '/reference/forge/forge-tree' },
          { text: 'forge geiger', link: '/reference/forge/forge-geiger' },
        ],
      },
      {
        text: 'Build Commands',
        link: '/reference/forge/build-commands',
        items: [
          { text: 'forge build', link: '/reference/forge/forge-build' },
          { text: 'forge clean', link: '/reference/forge/forge-clean' },
          { text: 'forge inspect', link: '/reference/forge/forge-inspect' },
        ],
      },
      {
        text: 'Test Commands',
        link: '/reference/forge/test-commands',
        items: [
          { text: 'forge test', link: '/reference/forge/forge-test' },
          { text: 'forge snapshot', link: '/reference/forge/forge-snapshot' },
          { text: 'forge coverage', link: '/reference/forge/forge-coverage' },
        ],
      },
      {
        text: 'Deploy Commands',
        link: '/reference/forge/deploy-commands',
        items: [
          { text: 'forge create', link: '/reference/forge/forge-create' },
          { text: 'forge verify-contract', link: '/reference/forge/forge-verify-contract' },
          { text: 'forge verify-check', link: '/reference/forge/forge-verify-check' },
          { text: 'forge flatten', link: '/reference/forge/forge-flatten' },
        ],
      },
      {
        text: 'Utility Commands',
        link: '/reference/forge/utility-commands',
        items: [
          { text: 'forge bind', link: '/reference/forge/forge-bind' },
          { text: 'forge cache', link: '/reference/forge/forge-cache' },
          { text: 'forge cache clean', link: '/reference/forge/forge-cache-clean' },
          { text: 'forge cache ls', link: '/reference/forge/forge-cache-ls' },
          { text: 'forge script', link: '/reference/forge/forge-script' },
          { text: 'forge upload-selectors', link: '/reference/forge/forge-upload-selectors' },
          { text: 'forge doc', link: '/reference/forge/forge-doc' },
        ],
      },
    ],
  },
  {
    text: 'Cast Commands',
    collapsed: true,
    items: [
      {
        text: 'General Commands',
        link: '/cast/reference/general-commands',
        items: [
          { text: 'cast', link: '/cast/reference/cast' },
          { text: 'cast help', link: '/cast/reference/cast-help' },
          { text: 'cast completions', link: '/cast/reference/cast-completions' },
        ],
      },
      {
        text: 'Chain Commands',
        link: '/cast/reference/chain-commands',
        items: [
          { text: 'cast chain-id', link: '/cast/reference/cast-chain-id' },
          { text: 'cast chain', link: '/cast/reference/cast-chain' },
          { text: 'cast client', link: '/cast/reference/cast-client' },
        ],
      },
      {
        text: 'Transaction Commands',
        link: '/cast/reference/transaction-commands',
        items: [
          { text: 'cast publish', link: '/cast/reference/cast-publish' },
          { text: 'cast receipt', link: '/cast/reference/cast-receipt' },
          { text: 'cast send', link: '/cast/reference/cast-send' },
          { text: 'cast mktx', link: '/cast/reference/cast-mktx' },
          { text: 'cast call', link: '/cast/reference/cast-call' },
          { text: 'cast rpc', link: '/cast/reference/cast-rpc' },
          { text: 'cast tx', link: '/cast/reference/cast-tx' },
          { text: 'cast run', link: '/cast/reference/cast-run' },
          { text: 'cast estimate', link: '/cast/reference/cast-estimate' },
          { text: 'cast access-list', link: '/cast/reference/cast-access-list' },
          { text: 'cast logs', link: '/cast/reference/cast-logs' },
        ],
      },
      {
        text: 'Block Commands',
        link: '/cast/reference/block-commands',
        items: [
          { text: 'cast find-block', link: '/cast/reference/cast-find-block' },
          { text: 'cast gas-price', link: '/cast/reference/cast-gas-price' },
          { text: 'cast block-number', link: '/cast/reference/cast-block-number' },
          { text: 'cast basefee', link: '/cast/reference/cast-basefee' },
          { text: 'cast block', link: '/cast/reference/cast-block' },
          { text: 'cast age', link: '/cast/reference/cast-age' },
        ],
      },
      {
        text: 'Account Commands',
        link: '/cast/reference/account-commands',
        items: [
          { text: 'cast balance', link: '/cast/reference/cast-balance' },
          { text: 'cast storage', link: '/cast/reference/cast-storage' },
          { text: 'cast proof', link: '/cast/reference/cast-proof' },
          { text: 'cast nonce', link: '/cast/reference/cast-nonce' },
          { text: 'cast code', link: '/cast/reference/cast-code' },
          { text: 'cast codesize', link: '/cast/reference/cast-codesize' },
        ],
      },
      {
        text: 'ENS Commands',
        link: '/cast/reference/ens-commands',
        items: [
          { text: 'cast lookup-address', link: '/cast/reference/cast-lookup-address' },
          { text: 'cast resolve-name', link: '/cast/reference/cast-resolve-name' },
          { text: 'cast namehash', link: '/cast/reference/cast-namehash' },
        ],
      },
      {
        text: 'Etherscan Commands',
        link: '/cast/reference/etherscan-commands',
        items: [
          { text: 'cast etherscan-source', link: '/cast/reference/cast-etherscan-source' },
        ],
      },
      {
        text: 'ABI Commands',
        link: '/cast/reference/abi-commands',
        items: [
          { text: 'cast abi-encode', link: '/cast/reference/cast-abi-encode' },
          { text: 'cast 4byte', link: '/cast/reference/cast-4byte' },
          { text: 'cast 4byte-calldata', link: '/cast/reference/cast-4byte-calldata' },
          { text: 'cast 4byte-event', link: '/cast/reference/cast-4byte-event' },
          { text: 'cast calldata', link: '/cast/reference/cast-calldata' },
          { text: 'cast decode-abi', link: '/cast/reference/cast-decode-abi' },
          { text: 'cast decode-calldata', link: '/cast/reference/cast-decode-calldata' },
          { text: 'cast pretty-calldata', link: '/cast/reference/cast-pretty-calldata' },
          { text: 'cast selectors', link: '/cast/reference/cast-selectors' },
          { text: 'cast upload-signature', link: '/cast/reference/cast-upload-signature' },
        ],
      },
      {
        text: 'Conversion Commands',
        link: '/cast/reference/conversion-commands',
        items: [
          { text: 'cast format-bytes32-string', link: '/cast/reference/cast-format-bytes32-string' },
          { text: 'cast from-bin', link: '/cast/reference/cast-from-bin' },
          { text: 'cast from-fixed-point', link: '/cast/reference/cast-from-fixed-point' },
          { text: 'cast from-rlp', link: '/cast/reference/cast-from-rlp' },
          { text: 'cast from-utf8', link: '/cast/reference/cast-from-utf8' },
          { text: 'cast from-wei', link: '/cast/reference/cast-from-wei' },
          { text: 'cast parse-bytes32-address', link: '/cast/reference/cast-parse-bytes32-address' },
          { text: 'cast parse-bytes32-string', link: '/cast/reference/cast-parse-bytes32-string' },
          { text: 'cast to-ascii', link: '/cast/reference/cast-to-ascii' },
          { text: 'cast to-base', link: '/cast/reference/cast-to-base' },
          { text: 'cast to-bytes32', link: '/cast/reference/cast-to-bytes32' },
          { text: 'cast to-dec', link: '/cast/reference/cast-to-dec' },
          { text: 'cast to-fixed-point', link: '/cast/reference/cast-to-fixed-point' },
          { text: 'cast to-hex', link: '/cast/reference/cast-to-hex' },
          { text: 'cast to-hexdata', link: '/cast/reference/cast-to-hexdata' },
          { text: 'cast to-int256', link: '/cast/reference/cast-to-int256' },
          { text: 'cast to-rlp', link: '/cast/reference/cast-to-rlp' },
          { text: 'cast to-uint256', link: '/cast/reference/cast-to-uint256' },
          { text: 'cast to-unit', link: '/cast/reference/cast-to-unit' },
          { text: 'cast to-wei', link: '/cast/reference/cast-to-wei' },
          { text: 'cast shl', link: '/cast/reference/cast-shl' },
          { text: 'cast shr', link: '/cast/reference/cast-shr' },
        ],
      },
      {
        text: 'Utility Commands',
        link: '/cast/reference/utility-commands',
        items: [
          { text: 'cast address-zero', link: '/cast/reference/cast-address-zero' },
          { text: 'cast sig', link: '/cast/reference/cast-sig' },
          { text: 'cast sig-event', link: '/cast/reference/cast-sig-event' },
          { text: 'cast keccak', link: '/cast/reference/cast-keccak' },
          { text: 'cast compute-address', link: '/cast/reference/cast-compute-address' },
          { text: 'cast create2', link: '/cast/reference/cast-create2' },
          { text: 'cast interface', link: '/cast/reference/cast-interface' },
          { text: 'cast index', link: '/cast/reference/cast-index' },
          { text: 'cast concat-hex', link: '/cast/reference/cast-concat-hex' },
          { text: 'cast max-int', link: '/cast/reference/cast-max-int' },
          { text: 'cast min-int', link: '/cast/reference/cast-min-int' },
          { text: 'cast max-uint', link: '/cast/reference/cast-max-uint' },
          { text: 'cast to-check-sum-address', link: '/cast/reference/cast-to-check-sum-address' },
        ],
      },
      {
        text: 'Wallet Commands',
        link: '/cast/reference/wallet-commands',
        items: [
          { text: 'cast wallet', link: '/cast/reference/cast-wallet' },
          { text: 'cast wallet new', link: '/cast/reference/cast-wallet-new' },
          { text: 'cast wallet new-mnemonic', link: '/cast/reference/cast-wallet-new-mnemonic' },
          { text: 'cast wallet address', link: '/cast/reference/cast-wallet-address' },
          { text: 'cast wallet sign', link: '/cast/reference/cast-wallet-sign' },
          { text: 'cast wallet vanity', link: '/cast/reference/cast-wallet-vanity' },
          { text: 'cast wallet verify', link: '/cast/reference/cast-wallet-verify' },
          { text: 'cast wallet import', link: '/cast/reference/cast-wallet-import' },
          { text: 'cast wallet list', link: '/cast/reference/cast-wallet-list' },
        ],
      },
    ],
  },
  {
    text: 'Anvil Reference',
    link: '/anvil/reference',
  },
  {
    text: 'Chisel Reference',
    link: '/chisel/reference',
  },
  {
    text: 'Config Reference',
    collapsed: true,
    items: [
      { text: 'Overview', link: '/reference/config/overview' },
      { text: 'Project', link: '/reference/config/project' },
      { text: 'Solidity Compiler', link: '/reference/config/solidity-compiler' },
      { text: 'Testing', link: '/reference/config/testing' },
      { text: 'In-line Configuration Testing', link: '/reference/config/inline-test-config' },
      { text: 'Formatter', link: '/reference/config/formatter' },
      { text: 'Documentation Generator', link: '/reference/config/doc-generator' },
      { text: 'Etherscan', link: '/reference/config/etherscan' },
    ],
  },
  {
    text: 'Cheatcodes Reference',
    collapsed: true,
    items: [
      {
        text: 'Environment',
        link: '/reference/cheatcodes/environment',
        items: [
          { text: 'warp', link: '/reference/cheatcodes/warp' },
          { text: 'roll', link: '/reference/cheatcodes/roll' },
          { text: 'fee', link: '/reference/cheatcodes/fee' },
          { text: 'getBlockTimestamp', link: '/reference/cheatcodes/get-block-timestamp' },
          { text: 'getBlockNumber', link: '/reference/cheatcodes/get-block-number' },
          { text: 'difficulty', link: '/reference/cheatcodes/difficulty' },
          { text: 'prevrandao', link: '/reference/cheatcodes/prevrandao' },
          { text: 'chainId', link: '/reference/cheatcodes/chain-id' },
          { text: 'store', link: '/reference/cheatcodes/store' },
          { text: 'load', link: '/reference/cheatcodes/load' },
          { text: 'etch', link: '/reference/cheatcodes/etch' },
          { text: 'deal', link: '/reference/cheatcodes/deal' },
          { text: 'prank', link: '/reference/cheatcodes/prank' },
          { text: 'startPrank', link: '/reference/cheatcodes/start-prank' },
          { text: 'stopPrank', link: '/reference/cheatcodes/stop-prank' },
          { text: 'readCallers', link: '/reference/cheatcodes/read-callers' },
          { text: 'record', link: '/reference/cheatcodes/record' },
          { text: 'accesses', link: '/reference/cheatcodes/accesses' },
          { text: 'recordLogs', link: '/reference/cheatcodes/record-logs' },
          { text: 'getRecordedLogs', link: '/reference/cheatcodes/get-recorded-logs' },
          { text: 'setNonce', link: '/reference/cheatcodes/set-nonce' },
          { text: 'getNonce', link: '/reference/cheatcodes/get-nonce' },
          { text: 'mockCall', link: '/reference/cheatcodes/mock-call' },
          { text: 'mockCalls', link: '/reference/cheatcodes/mock-calls' },
          { text: 'mockCallRevert', link: '/reference/cheatcodes/mock-call-revert' },
          { text: 'mockFunction', link: '/reference/cheatcodes/mock-function' },
          { text: 'clearMockedCalls', link: '/reference/cheatcodes/clear-mocked-calls' },
          { text: 'coinbase', link: '/reference/cheatcodes/coinbase' },
          { text: 'broadcast', link: '/reference/cheatcodes/broadcast' },
          { text: 'startBroadcast', link: '/reference/cheatcodes/start-broadcast' },
          { text: 'stopBroadcast', link: '/reference/cheatcodes/stop-broadcast' },
          { text: 'pauseGasMetering', link: '/reference/cheatcodes/pause-gas-metering' },
          { text: 'resetGasMetering', link: '/reference/cheatcodes/reset-gas-metering' },
          { text: 'resumeGasMetering', link: '/reference/cheatcodes/resume-gas-metering' },
          { text: 'txGasPrice', link: '/reference/cheatcodes/tx-gas-price' },
          { text: 'startStateDiffRecording', link: '/reference/cheatcodes/start-state-diff-recording' },
          { text: 'stopAndReturnStateDiff', link: '/reference/cheatcodes/stop-and-return-state-diff' },
          { text: 'snapshotState', link: '/reference/cheatcodes/state-snapshots' },
          { text: 'snapshotGas', link: '/reference/cheatcodes/gas-snapshots' },
          { text: 'isContext', link: '/reference/cheatcodes/is-context' },
        ],
      },
      {
        text: 'Assertions',
        link: '/reference/cheatcodes/assertions',
        items: [
          { text: 'expectRevert', link: '/reference/cheatcodes/expect-revert' },
          { text: 'expectEmit', link: '/reference/cheatcodes/expect-emit' },
          { text: 'expectCall', link: '/reference/cheatcodes/expect-call' },
        ],
      },
      {
        text: 'Fuzzer',
        link: '/reference/cheatcodes/fuzzer',
        items: [
          { text: 'assume', link: '/reference/cheatcodes/assume' },
          { text: 'assumeNoRevert', link: '/reference/cheatcodes/assume-no-revert' },
        ],
      },
      {
        text: 'Forking',
        link: '/reference/cheatcodes/forking',
        items: [
          { text: 'createFork', link: '/reference/cheatcodes/create-fork' },
          { text: 'selectFork', link: '/reference/cheatcodes/select-fork' },
          { text: 'createSelectFork', link: '/reference/cheatcodes/create-select-fork' },
          { text: 'activeFork', link: '/reference/cheatcodes/active-fork' },
          { text: 'rollFork', link: '/reference/cheatcodes/roll-fork' },
          { text: 'makePersistent', link: '/reference/cheatcodes/make-persistent' },
          { text: 'revokePersistent', link: '/reference/cheatcodes/revoke-persistent' },
          { text: 'isPersistent', link: '/reference/cheatcodes/is-persistent' },
          { text: 'allowCheatcodes', link: '/reference/cheatcodes/allow-cheatcodes' },
          { text: 'transact', link: '/reference/cheatcodes/transact' },
        ],
      },
      {
        text: 'External',
        link: '/reference/cheatcodes/external',
        items: [
          { text: 'ffi', link: '/reference/cheatcodes/ffi' },
          { text: 'prompt', link: '/reference/cheatcodes/prompt' },
          { text: 'projectRoot', link: '/reference/cheatcodes/project-root' },
          { text: 'getCode', link: '/reference/cheatcodes/get-code' },
          { text: 'getDeployedCode', link: '/reference/cheatcodes/get-deployed-code' },
          { text: 'sleep', link: '/reference/cheatcodes/sleep' },
          { text: 'unixTime', link: '/reference/cheatcodes/unix-time' },
          { text: 'setEnv', link: '/reference/cheatcodes/set-env' },
          { text: 'envOr', link: '/reference/cheatcodes/env-or' },
          { text: 'envBool', link: '/reference/cheatcodes/env-bool' },
          { text: 'envUint', link: '/reference/cheatcodes/env-uint' },
          { text: 'envInt', link: '/reference/cheatcodes/env-int' },
          { text: 'envAddress', link: '/reference/cheatcodes/env-address' },
          { text: 'envBytes32', link: '/reference/cheatcodes/env-bytes32' },
          { text: 'envString', link: '/reference/cheatcodes/env-string' },
          { text: 'envBytes', link: '/reference/cheatcodes/env-bytes' },
          { text: 'keyExists', link: '/reference/cheatcodes/key-exists' },
          { text: 'keyExistsJson', link: '/reference/cheatcodes/key-exists-json' },
          { text: 'keyExistsToml', link: '/reference/cheatcodes/key-exists-toml' },
          { text: 'parseJson', link: '/reference/cheatcodes/parse-json' },
          { text: 'parseToml', link: '/reference/cheatcodes/parse-toml' },
          { text: 'parseJsonKeys', link: '/reference/cheatcodes/parse-json-keys' },
          { text: 'parseTomlKeys', link: '/reference/cheatcodes/parse-toml-keys' },
          { text: 'serializeJson', link: '/reference/cheatcodes/serialize-json' },
          { text: 'writeJson', link: '/reference/cheatcodes/write-json' },
          { text: 'writeToml', link: '/reference/cheatcodes/write-toml' },
        ],
      },
      {
        text: 'Signing',
        link: '/reference/cheatcodes/signing',
        items: [
          { text: 'sign', link: '/reference/cheatcodes/sign' },
          { text: 'signDelegation', link: '/reference/cheatcodes/sign-delegation' },
        ],
      },
      {
        text: 'Utilities',
        link: '/reference/cheatcodes/utilities',
        items: [
          { text: 'addr', link: '/reference/cheatcodes/addr' },
          { text: 'skip', link: '/reference/cheatcodes/skip' },
          { text: 'label', link: '/reference/cheatcodes/label' },
          { text: 'getLabel', link: '/reference/cheatcodes/get-label' },
          { text: 'deriveKey', link: '/reference/cheatcodes/derive-key' },
          { text: 'parseBytes', link: '/reference/cheatcodes/parse-bytes' },
          { text: 'parseAddress', link: '/reference/cheatcodes/parse-address' },
          { text: 'parseUint', link: '/reference/cheatcodes/parse-uint' },
          { text: 'parseInt', link: '/reference/cheatcodes/parse-int' },
          { text: 'parseBytes32', link: '/reference/cheatcodes/parse-bytes32' },
          { text: 'parseBool', link: '/reference/cheatcodes/parse-bool' },
          { text: 'rememberKey', link: '/reference/cheatcodes/remember-key' },
          { text: 'toString', link: '/reference/cheatcodes/to-string' },
          { text: 'breakpoint', link: '/reference/cheatcodes/breakpoint' },
          { text: 'createWallet', link: '/reference/cheatcodes/create-wallet' },
          { text: 'copyStorage', link: '/reference/cheatcodes/copy-storage' },
          { text: 'setArbitraryStorage', link: '/reference/cheatcodes/set-arbitrary-storage' },
        ],
      },
      { text: 'RPC', link: '/reference/cheatcodes/rpc' },
      { text: 'Files', link: '/reference/cheatcodes/fs' },
    ],
  },
  {
    text: 'Forge Standard Library Reference',
    collapsed: true,
    items: [
      { text: 'Std Logs', link: '/reference/forge-std/std-logs' },
      {
        text: 'Std Assertions',
        link: '/reference/forge-std/std-assertions',
        items: [
          { text: 'fail', link: '/reference/forge-std/fail' },
          { text: 'assertTrue', link: '/reference/forge-std/assertTrue' },
          { text: 'assertFalse', link: '/reference/forge-std/assertFalse' },
          { text: 'assertEq', link: '/reference/forge-std/assertEq' },
          { text: 'assertEqDecimal', link: '/reference/forge-std/assertEqDecimal' },
          { text: 'assertNotEq', link: '/reference/forge-std/assertNotEq' },
          { text: 'assertNotEqDecimal', link: '/reference/forge-std/assertNotEqDecimal' },
          { text: 'assertLt', link: '/reference/forge-std/assertLt' },
          { text: 'assertLtDecimal', link: '/reference/forge-std/assertLtDecimal' },
          { text: 'assertGt', link: '/reference/forge-std/assertGt' },
          { text: 'assertGtDecimal', link: '/reference/forge-std/assertGtDecimal' },
          { text: 'assertLe', link: '/reference/forge-std/assertLe' },
          { text: 'assertLeDecimal', link: '/reference/forge-std/assertLeDecimal' },
          { text: 'assertGe', link: '/reference/forge-std/assertGe' },
          { text: 'assertGeDecimal', link: '/reference/forge-std/assertGeDecimal' },
          { text: 'assertApproxEqAbs', link: '/reference/forge-std/assertApproxEqAbs' },
          { text: 'assertApproxEqAbsDecimal', link: '/reference/forge-std/assertApproxEqAbsDecimal' },
          { text: 'assertApproxEqRel', link: '/reference/forge-std/assertApproxEqRel' },
          { text: 'assertApproxEqRelDecimal', link: '/reference/forge-std/assertApproxEqRelDecimal' },
        ],
      },
      {
        text: 'Std Cheats',
        link: '/reference/forge-std/std-cheats',
        items: [
          { text: 'skip', link: '/reference/forge-std/skip' },
          { text: 'rewind', link: '/reference/forge-std/rewind' },
          { text: 'hoax', link: '/reference/forge-std/hoax' },
          { text: 'startHoax', link: '/reference/forge-std/startHoax' },
          { text: 'deal', link: '/reference/forge-std/deal' },
          { text: 'deployCode', link: '/reference/forge-std/deployCode' },
          { text: 'deployCodeTo', link: '/reference/forge-std/deployCodeTo' },
          { text: 'bound', link: '/reference/forge-std/bound' },
          { text: 'changePrank', link: '/reference/forge-std/change-prank' },
          { text: 'makeAddr', link: '/reference/forge-std/make-addr' },
          { text: 'makeAddrAndKey', link: '/reference/forge-std/make-addr-and-key' },
          { text: 'noGasMetering', link: '/reference/forge-std/noGasMetering' },
          { text: 'assumeNoPrecompiles', link: '/reference/forge-std/assume-no-precompiles' },
          { text: 'assumePayable', link: '/reference/forge-std/assume-payable' },
        ],
      },
      {
        text: 'Std Errors',
        link: '/reference/forge-std/std-errors',
        items: [
          { text: 'assertionError', link: '/reference/forge-std/assertionError' },
          { text: 'arithmeticError', link: '/reference/forge-std/arithmeticError' },
          { text: 'divisionError', link: '/reference/forge-std/divisionError' },
          { text: 'enumConversionError', link: '/reference/forge-std/enumConversionError' },
          { text: 'encodeStorageError', link: '/reference/forge-std/encodeStorageError' },
          { text: 'popError', link: '/reference/forge-std/popError' },
          { text: 'indexOOBError', link: '/reference/forge-std/indexOOBError' },
          { text: 'memOverflowError', link: '/reference/forge-std/memOverflowError' },
          { text: 'zeroVarError', link: '/reference/forge-std/zeroVarError' },
        ],
      },
      {
        text: 'Std Storage',
        link: '/reference/forge-std/std-storage',
        items: [
          { text: 'target', link: '/reference/forge-std/target' },
          { text: 'sig', link: '/reference/forge-std/sig' },
          { text: 'with_key', link: '/reference/forge-std/with_key' },
          { text: 'depth', link: '/reference/forge-std/depth' },
          { text: 'enable_packed_slots', link: '/reference/forge-std/enable_packed_slots' },
          { text: 'checked_write', link: '/reference/forge-std/checked_write' },
          { text: 'find', link: '/reference/forge-std/find' },
          { text: 'read', link: '/reference/forge-std/read' },
        ],
      },
      {
        text: 'Std Math',
        link: '/reference/forge-std/std-math',
        items: [
          { text: 'abs', link: '/reference/forge-std/abs' },
          { text: 'delta', link: '/reference/forge-std/delta' },
          { text: 'percentDelta', link: '/reference/forge-std/percentDelta' },
        ],
      },
      {
        text: 'Script Utils',
        link: '/reference/forge-std/script-utils',
        items: [
          { text: 'computeCreateAddress', link: '/reference/forge-std/compute-create-address' },
          { text: 'deriveRememberKey', link: '/reference/forge-std/derive-remember-key' },
        ],
      },
      { text: 'Console Logging', link: '/reference/forge-std/console-log' },
    ],
  },
  {
    text: 'DSTest Reference',
    link: '/reference/ds-test',
  },
];