import { SidebarItem } from "vocs";

export const forgeCliReference: SidebarItem = {
    text: "Reference",
    collapsed: true,
    items: [
        { text: "forge", link: "/reference/forge/forge" },
        {
            text: "Build Commands",
            collapsed: true,
            items: [
                { text: "forge build", link: "/reference/forge/build" },
                { text: "forge cache clean", link: "/reference/forge/cache/clean" },
                { text: "forge clean", link: "/reference/forge/clean" },
                { text: "forge inspect", link: "/reference/forge/inspect" },
                { text: "forge soldeer clean", link: "/reference/forge/soldeer/clean" },
            ],
        },
        {
            text: "Deploy Commands",
            collapsed: true,
            items: [
                { text: "forge create", link: "/reference/forge/create" },
                { text: "forge flatten", link: "/reference/forge/flatten" },
                { text: "forge verify-check", link: "/reference/forge/verify-check" },
                { text: "forge verify-contract", link: "/reference/forge/verify-contract" },
            ],
        },
        {
            text: "General Commands",
            collapsed: true,
            items: [
                { text: "forge completions", link: "/reference/forge/completions" },
            ],
        },
        {
            text: "Project Commands",
            collapsed: true,
            items: [
                { text: "forge clone", link: "/reference/forge/clone" },
                { text: "forge config", link: "/reference/forge/config" },
                { text: "forge geiger", link: "/reference/forge/geiger" },
                { text: "forge init", link: "/reference/forge/init" },
                { text: "forge install", link: "/reference/forge/install" },
                { text: "forge remappings", link: "/reference/forge/remappings" },
                { text: "forge remove", link: "/reference/forge/remove" },
                { text: "forge soldeer init", link: "/reference/forge/soldeer/init" },
                { text: "forge soldeer install", link: "/reference/forge/soldeer/install" },
                { text: "forge soldeer update", link: "/reference/forge/soldeer/update" },
                { text: "forge tree", link: "/reference/forge/tree" },
                { text: "forge update", link: "/reference/forge/update" },
            ],
        },
        {
            text: "Test Commands",
            collapsed: true,
            items: [
                { text: "forge coverage", link: "/reference/forge/coverage" },
                { text: "forge snapshot", link: "/reference/forge/snapshot" },
                { text: "forge test", link: "/reference/forge/test" },
            ],
        },
        {
            text: "Utility Commands",
            collapsed: true,
            items: [
                { text: "forge bind", link: "/reference/forge/bind" },
                { text: "forge bind-json", link: "/reference/forge/bind-json" },
                { text: "forge cache", link: "/reference/forge/cache" },
                { text: "forge cache ls", link: "/reference/forge/cache/ls" },
                { text: "forge compiler", link: "/reference/forge/compiler" },
                { text: "forge compiler resolve", link: "/reference/forge/compiler/resolve" },
                { text: "forge doc", link: "/reference/forge/doc" },
                { text: "forge eip712", link: "/reference/forge/eip712" },
                { text: "forge fmt", link: "/reference/forge/fmt" },
                { text: "forge lint", link: "/reference/forge/lint" },
                { text: "forge script", link: "/reference/forge/script" },
                { text: "forge selectors", link: "/reference/forge/selectors" },
                { text: "forge selectors cache", link: "/reference/forge/selectors/cache" },
                { text: "forge selectors collision", link: "/reference/forge/selectors/collision" },
                { text: "forge selectors find", link: "/reference/forge/selectors/find" },
                { text: "forge selectors list", link: "/reference/forge/selectors/list" },
                { text: "forge selectors upload", link: "/reference/forge/selectors/upload" },
                { text: "forge soldeer", link: "/reference/forge/soldeer" },
                { text: "forge soldeer login", link: "/reference/forge/soldeer/login" },
                { text: "forge soldeer push", link: "/reference/forge/soldeer/push" },
                { text: "forge soldeer uninstall", link: "/reference/forge/soldeer/uninstall" },
                { text: "forge soldeer version", link: "/reference/forge/soldeer/version" },
                { text: "forge verify-bytecode", link: "/reference/forge/verify-bytecode" },
            ],
        },
    ],
};
