import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { parseArgs } from "node:util";
import { pathToFileURL } from "node:url";
import { renderExamples, runExample } from "./lint-examples.ts";

export const groups = {
  High: "High severity",
  Med: "Medium severity",
  Low: "Low severity",
  Info: "Informational",
  Gas: "Gas optimization",
  CodeSize: "Code size",
} as const;
type Severity = keyof typeof groups;
export type LintDoc = { id: string; severity: Severity; title: string; body: string };
type Manifest = {
  schemaVersion: 1;
  source: { repository: "foundry-rs/foundry"; commit: string; path: "crates/lint/docs" };
  pages: Record<string, string>;
  navigation: Record<string, string>;
};

const manifestPath = "scripts/lint-docs-manifest.json";
const pagesPath = "src/pages/forge/linting";
const generatedNotice = "{/* Generated by import:lints from Foundry. Do not edit directly. */}";
const navigation = {
  "sidebar/forge.ts": ["  // BEGIN GENERATED LINTS", "  // END GENERATED LINTS"],
  "src/pages/forge/linting.mdx": ["{/* BEGIN GENERATED LINTS */}", "{/* END GENERATED LINTS */}"],
} as const;

const hash = (text: string) => createHash("sha256").update(text).digest("hex");
const hasOwn = (value: object, key: string) => Object.prototype.hasOwnProperty.call(value, key);
const read = (root: string, path: string) => readFileSync(join(root, path), "utf8");
const git = (foundry: string, ...args: string[]) =>
  execFileSync("git", ["-C", foundry, ...args], { encoding: "utf8" }).trim();

// Change Markdown headings, never example source (including longer or tilde fences).
export function shiftHeadings(text: string, direction: 1 | -1): string {
  let fence: { char: string; length: number } | undefined;
  return text
    .split("\n")
    .map((line) => {
      const marker = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/);
      if (fence) {
        if (
          marker &&
          marker[1][0] === fence.char &&
          marker[1].length >= fence.length &&
          !marker[2].trim()
        )
          fence = undefined;
        return line;
      }
      if (marker) {
        fence = { char: marker[1][0], length: marker[1].length };
        return line;
      }
      return line.replace(/^(#{1,6}) /, (_, heading: string) => {
        const length = heading.length + direction;
        if (length < 1 || length > 6) throw new Error("cannot shift Markdown heading depth");
        return `${"#".repeat(length)} `;
      });
    })
    .join("\n");
}

export function canonicalBody(page: string): string {
  return shiftHeadings(
    page.replace(/^---\n[\s\S]*?\n---\n+/, "").replace(`${generatedNotice}\n\n`, ""),
    -1,
  ).trim();
}

function validateLintDoc(body: string, id: string): void {
  const lines: string[] = [];
  let fence: { char: string; length: number; solidity: boolean; content: boolean } | undefined;
  for (const line of body.split("\n")) {
    const marker = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/);
    if (fence) {
      if (
        marker &&
        marker[1][0] === fence.char &&
        marker[1].length >= fence.length &&
        !marker[2].trim()
      ) {
        if (fence.solidity && fence.content) lines.push("\0solidity");
        fence = undefined;
      } else if (line.trim()) fence.content = true;
    } else if (marker) {
      fence = {
        char: marker[1][0],
        length: marker[1].length,
        solidity: marker[2].trim() === "solidity",
        content: false,
      };
    } else lines.push(line);
  }
  const fail = (reason: string): never => {
    throw new Error(`${id}: ${reason}`);
  };
  if (fence) fail("unclosed code fence");
  const text = lines.join("\n");
  const sections = text
    .split(/^## /m)
    .slice(1)
    .map((section) => {
      const [heading, ...content] = section.split("\n");
      return { heading, content: content.join("\n").trim() };
    });
  const what = sections.findIndex(({ heading }) => heading === "What it does");
  const why = sections.findIndex(({ heading }) =>
    /^Why (is this bad|restrict this)\?$/.test(heading),
  );
  const example = sections.findIndex(({ heading }) => heading === "Example");
  if (!(what >= 0 && why > what && example > why))
    fail("required sections missing or out of order");
  for (const heading of ["What it does", "Example"])
    if (sections.filter((section) => section.heading === heading).length !== 1)
      fail(`expected one ${heading} section`);
  if (
    sections.filter(({ heading }) => /^Why (is this bad|restrict this)\?$/.test(heading)).length !==
    1
  )
    fail("expected exactly one rationale section");
  for (const index of [what, why])
    if (!sections[index].content.replaceAll("\0solidity", "").trim())
      fail(`${sections[index].heading} section must explain the lint`);
  if (/^### (Bad|Good)$/m.test(text)) fail("replace Bad/Good headings with Use instead:");
  const examples = sections[example].content.split(/^Use instead:$/m);
  if (examples.length !== 2 || !examples.every((part) => part.includes("\0solidity")))
    fail("expected a Solidity example on each side of Use instead:");
}

export function readLintDocs(foundry: string): LintDoc[] {
  const solDir = join(foundry, "crates/lint/src/sol");
  const registry = ["high", "med", "low", "info", "gas", "codesize"]
    .map(
      (group) =>
        readFileSync(join(solDir, group, "mod.rs"), "utf8").split("register_lints!(")[1] ?? "",
    )
    .join("\n");
  const declarations = readdirSync(solDir, { recursive: true })
    .filter((file): file is string => typeof file === "string" && file.endsWith(".rs"))
    .flatMap((file) => [
      ...readFileSync(join(solDir, file), "utf8").matchAll(
        /declare_forge_lint!\(\s*([A-Z_0-9]+),\s*Severity::(\w+),\s*"([a-z0-9-]+)"/g,
      ),
    ])
    .filter((match) => new RegExp(`\\b${match[1]}\\b`).test(registry));
  if (!declarations.length) throw new Error("no registered Foundry lints found");
  const ids = new Set<string>();
  return declarations
    .map(([, , severity, id]) => {
      if (ids.has(id)) throw new Error(`duplicate lint ID: ${id}`);
      ids.add(id);
      const body = read(foundry, `crates/lint/docs/${id}.md`).trim();
      const title = body.match(/^# (.+)\n/)?.[1];
      if (
        !title ||
        !hasOwn(groups, severity) ||
        !body.includes(`**ID**: \`${id}\``) ||
        !body.includes(`**Severity**: \`${severity}\``)
      )
        throw new Error(`${id}: invalid canonical title or metadata`);
      validateLintDoc(body, id);
      return { id, severity: severity as Severity, title, body };
    })
    .sort((a, b) => a.id.localeCompare(b.id, "en"));
}

export function renderPage(lint: LintDoc): string {
  const description = JSON.stringify(lint.title.replace(/`/g, ""));
  return `---\ndescription: ${description}\n---\n\n${generatedNotice}\n\n${shiftHeadings(lint.body, 1)}\n`;
}

function region(
  text: string,
  start: string,
  end: string,
): { before: string; body: string; after: string } {
  const parts = text.split(start);
  if (parts.length !== 2) throw new Error(`expected exactly one ${start} marker`);
  const tail = parts[1].split(end);
  if (tail.length !== 2 || parts[0].includes(end))
    throw new Error(`expected exactly one ${end} marker`);
  return { before: parts[0] + start, body: tail[0], after: end + tail[1] };
}

// Build every replacement before writing, so invalid input cannot partially update the book.
export function planImport(root: string, foundry: string, forge = "forge"): Map<string, string> {
  const commit = git(foundry, "rev-parse", "HEAD");
  if (!/^[a-f0-9]{40}$/.test(commit)) throw new Error("expected a full Foundry commit SHA");
  if (git(foundry, "status", "--porcelain", "--", "crates/lint"))
    throw new Error("commit changes under crates/lint before importing reproducible documentation");
  const lints = readLintDocs(foundry);
  const files = new Map<string, string>();
  const manifest: Manifest = {
    schemaVersion: 1,
    source: { repository: "foundry-rs/foundry", commit, path: "crates/lint/docs" },
    pages: {},
    navigation: {},
  };
  for (const lint of lints) {
    const body = renderExamples(lint.body, lint.id, (source, id) => runExample(source, id, forge));
    const page = renderPage({ ...lint, body });
    files.set(`${pagesPath}/${lint.id}.mdx`, page);
    manifest.pages[lint.id] = hash(page);
  }
  // Retain removed lint URLs with a legacy notice rather than deleting published pages.
  for (const file of readdirSync(join(root, pagesPath)).filter((file) => file.endsWith(".mdx"))) {
    if (hasOwn(manifest.pages, file.slice(0, -4))) continue;
    const path = `${pagesPath}/${file}`;
    const page = read(root, path);
    validateLintDoc(canonicalBody(page), file.slice(0, -4));
    if (/^status: legacy$/m.test(page.split("---")[1] ?? "")) continue;
    if (!page.startsWith("---\n"))
      throw new Error(`${file}: cannot preserve page without frontmatter`);
    files.set(
      path,
      page
        .replace(/^---\n/, "---\nstatus: legacy\n")
        .replace(generatedNotice, "")
        .replace(
          /^(## .+)$/m,
          "$1\n\n:::note[Legacy lint]\nThis lint is not registered in the imported Foundry revision.\n:::",
        ),
    );
  }
  const sections = Object.entries(groups).map(([severity, title]) => ({
    title,
    lints: lints.filter((lint) => lint.severity === severity),
  }));
  const sidebar = sections
    .map(({ title, lints }) =>
      lints.length <= 1
        ? `  ruleGroup(${JSON.stringify(title)}, [${lints.map(({ id }) => JSON.stringify(id)).join(", ")}]),`
        : `  ruleGroup(${JSON.stringify(title)}, [\n${lints.map(({ id }) => `    "${id}",`).join("\n")}\n  ]),`,
    )
    .join("\n");
  const index = sections
    .map(
      ({ title, lints }) =>
        `#### ${title}\n\n${lints
          .map((lint) => {
            const introduction = lint.body
              .split(/\*\*ID\*\*: `[^`]+`\s*\n/)[1]
              ?.split(/^## /m)[0]
              .trim()
              .replace(/\s*\n\s*/g, " ");
            const what = lint.body
              .split(/^## What it does\n+/m)[1]
              ?.split(/\n\n|^## /m)[0]
              .trim()
              .replace(/\s*\n\s*/g, " ");
            const summary = introduction || (what && !what.endsWith(":") ? what : lint.title);
            return `- [\`${lint.id}\`](/forge/linting/${lint.id}) — ${summary}`;
          })
          .join("\n")}`,
    )
    .join("\n\n");
  for (const [path, [start, end]] of Object.entries(navigation)) {
    const { before, after } = region(read(root, path), start, end);
    const body = path.endsWith(".ts") ? `\n${sidebar}\n` : `\n\n${index}\n\n`;
    files.set(path, before + body + after);
    manifest.navigation[path] = hash(body);
  }
  files.set(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  return files;
}

export function checkImportedDocs(root: string): void {
  const manifest = JSON.parse(read(root, manifestPath)) as Manifest;
  if (
    manifest.schemaVersion !== 1 ||
    manifest.source.repository !== "foundry-rs/foundry" ||
    manifest.source.path !== "crates/lint/docs" ||
    !/^[a-f0-9]{40}$/.test(manifest.source.commit) ||
    !Object.keys(manifest.pages).length
  )
    throw new Error("invalid lint import manifest");
  const failures: string[] = [];
  for (const [id, expected] of Object.entries(manifest.pages)) {
    if (!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(id))
      throw new Error(`invalid manifest lint ID: ${id}`);
    if (hash(read(root, `${pagesPath}/${id}.mdx`)) !== expected) failures.push(id);
  }
  for (const file of readdirSync(join(root, pagesPath)).filter((file) => file.endsWith(".mdx"))) {
    const page = read(root, `${pagesPath}/${file}`);
    renderExamples(canonicalBody(page), file.slice(0, -4), () => {
      throw new Error(`${file}: unresolved {{produces}}; regenerate the lint import`);
    });
    validateLintDoc(canonicalBody(page), file.slice(0, -4));
    if (
      !hasOwn(manifest.pages, file.slice(0, -4)) &&
      !/^status: legacy$/m.test(page.split("---")[1] ?? "")
    )
      failures.push(`${file}: unimported active page`);
  }
  for (const [path, [start, end]] of Object.entries(navigation)) {
    if (hash(region(read(root, path), start, end).body) !== manifest.navigation[path])
      failures.push(path);
  }
  if (failures.length)
    throw new Error(
      `generated lint documentation changed; run import:lints -- --foundry <checkout>:\n${failures.join("\n")}`,
    );
}

export function main(
  args = process.argv.slice(2),
  root = resolve(import.meta.dirname, ".."),
): void {
  const { values } = parseArgs({
    args: args.filter((arg) => arg !== "--"),
    options: {
      foundry: { type: "string" },
      forge: { type: "string" },
      check: { type: "boolean" },
      help: { type: "boolean" },
    },
  });
  if (values.help) {
    console.log(
      "Usage: vp run import:lints -- --foundry <checkout> [--forge <binary>] [--check]\n       vp run import:lints -- --check\n\nImport committed Foundry lint pages and navigation. Use a Forge binary matching the source.\n--check never writes files; without --foundry it checks the committed import manifest offline.",
    );
    return;
  }
  if (!values.foundry) {
    if (!values.check) throw new Error("--foundry <checkout> is required when importing");
    checkImportedDocs(root);
    console.log("Imported lint documentation matches the committed manifest.");
    return;
  }
  const files = planImport(root, resolve(values.foundry), values.forge);
  const changed = [...files].filter(([path, text]) => {
    try {
      return read(root, path) !== text;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return true;
      throw error;
    }
  });
  if (values.check && changed.length)
    throw new Error(`lint import is stale:\n${changed.map(([path]) => path).join("\n")}`);
  if (!values.check) for (const [path, text] of changed) writeFileSync(join(root, path), text);
  console.log(
    `${values.check ? "Checked" : "Imported"} lint documentation; ${changed.length} changed files.`,
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) main();
