## Utility Commands

- [cast address-zero](./cast-address-zero.md)
- [cast sig](./cast-sig.md)
- [cast sig-event](./cast-sig-event.md)
- [cast keccak](./cast-keccak.md)
- [cast compute-address](./cast-compute-address.md)
- [cast create2](./cast-create2.md)
- [cast interface](./cast-interface.md)
- [cast index](./cast-index.md)
- [cast concat-hex](./cast-concat-hex.md)
- [cast max-int](./cast-max-int.md)
- [cast min-int](./cast-min-int.md)
- [cast max-uint](./cast-max-uint.md)
- [cast to-check-sum-address](./cast-to-check-sum-address.md)
