name: build

permissions: {}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: vocs build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "24"

      - name: Install bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - name: Build Vocs
        run: bun install && bun run build
